// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrSearchHandlerFunc turns a function with the right signature into a search handler
type NrSearchHandlerFunc func(NrSearchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrSearchHandlerFunc) Handle(params NrSearchParams) middleware.Responder {
	return fn(params)
}

// NrSearchHandler interface for that can handle valid search params
type NrSearchHandler interface {
	Handle(NrSearchParams) middleware.Responder
}

// NewNrSearch creates a new http.Handler for the search operation
func NewNrSearch(ctx *middleware.Context, handler NrSearchHandler) *NrSearch {
	return &NrSearch{Context: ctx, Handler: handler}
}

/*NrSearch swagger:route GET /search Search search

搜索

搜索

*/
type NrSearch struct {
	Context *middleware.Context
	Handler NrSearchHandler
}

func (o *NrSearch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrSearchParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
