// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi jinlinonline
jinlinonline


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /joe9724/jinlinonline/1.0.0
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <64060764@qq.com>

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
