// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityFieldListHandlerFunc turns a function with the right signature into a activity field list handler
type NrActivityFieldListHandlerFunc func(NrActivityFieldListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityFieldListHandlerFunc) Handle(params NrActivityFieldListParams) middleware.Responder {
	return fn(params)
}

// NrActivityFieldListHandler interface for that can handle valid activity field list params
type NrActivityFieldListHandler interface {
	Handle(NrActivityFieldListParams) middleware.Responder
}

// NewNrActivityFieldList creates a new http.Handler for the activity field list operation
func NewNrActivityFieldList(ctx *middleware.Context, handler NrActivityFieldListHandler) *NrActivityFieldList {
	return &NrActivityFieldList{Context: ctx, Handler: handler}
}

/*NrActivityFieldList swagger:route GET /activity/field/list Activity activityFieldList

活动场地

活动场地

*/
type NrActivityFieldList struct {
	Context *middleware.Context
	Handler NrActivityFieldListHandler
}

func (o *NrActivityFieldList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityFieldListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
