// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "jinlingonlineapi/models"
)

// ActivityFieldListOKCode is the HTTP code returned for type ActivityFieldListOK
const ActivityFieldListOKCode int = 200

/*ActivityFieldListOK 获取列表

swagger:response activityFieldListOK
*/
type ActivityFieldListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2007 `json:"body,omitempty"`
}

// NewActivityFieldListOK creates ActivityFieldListOK with default headers values
func NewActivityFieldListOK() *ActivityFieldListOK {
	return &ActivityFieldListOK{}
}

// WithPayload adds the payload to the activity field list o k response
func (o *ActivityFieldListOK) WithPayload(payload *models.InlineResponse2007) *ActivityFieldListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity field list o k response
func (o *ActivityFieldListOK) SetPayload(payload *models.InlineResponse2007) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityFieldListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityFieldListDefault error

swagger:response activityFieldListDefault
*/
type NrActivityFieldListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityFieldListDefault creates NrActivityFieldListDefault with default headers values
func NewNrActivityFieldListDefault(code int) *NrActivityFieldListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityFieldListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity field list default response
func (o *NrActivityFieldListDefault) WithStatusCode(code int) *NrActivityFieldListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity field list default response
func (o *NrActivityFieldListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity field list default response
func (o *NrActivityFieldListDefault) WithPayload(payload *models.Error) *NrActivityFieldListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity field list default response
func (o *NrActivityFieldListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityFieldListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
