// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityListSponsorHandlerFunc turns a function with the right signature into a activity list sponsor handler
type NrActivityListSponsorHandlerFunc func(NrActivityListSponsorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityListSponsorHandlerFunc) Handle(params NrActivityListSponsorParams) middleware.Responder {
	return fn(params)
}

// NrActivityListSponsorHandler interface for that can handle valid activity list sponsor params
type NrActivityListSponsorHandler interface {
	Handle(NrActivityListSponsorParams) middleware.Responder
}

// NewNrActivityListSponsor creates a new http.Handler for the activity list sponsor operation
func NewNrActivityListSponsor(ctx *middleware.Context, handler NrActivityListSponsorHandler) *NrActivityListSponsor {
	return &NrActivityListSponsor{Context: ctx, Handler: handler}
}

/*NrActivityListSponsor swagger:route GET /activity/list/sponsor Activity activityListSponsor

活动赞助商列表

活动列表

*/
type NrActivityListSponsor struct {
	Context *middleware.Context
	Handler NrActivityListSponsorHandler
}

func (o *NrActivityListSponsor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityListSponsorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
