// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// NrActivityFavURL generates an URL for the activity fav operation
type NrActivityFavURL struct {
	Action      *string
	Key         *string
	ServiceType *int64
	Status      *int64
	Title       *string
	Type        *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NrActivityFavURL) WithBasePath(bp string) *NrActivityFavURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NrActivityFavURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *NrActivityFavURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/activity/fav"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/joe9724/jinlinonline/1.0.0"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var action string
	if o.Action != nil {
		action = *o.Action
	}
	if action != "" {
		qs.Set("action", action)
	}

	var key string
	if o.Key != nil {
		key = *o.Key
	}
	if key != "" {
		qs.Set("key", key)
	}

	var serviceType string
	if o.ServiceType != nil {
		serviceType = swag.FormatInt64(*o.ServiceType)
	}
	if serviceType != "" {
		qs.Set("serviceType", serviceType)
	}

	var status string
	if o.Status != nil {
		status = swag.FormatInt64(*o.Status)
	}
	if status != "" {
		qs.Set("status", status)
	}

	var title string
	if o.Title != nil {
		title = *o.Title
	}
	if title != "" {
		qs.Set("title", title)
	}

	var typeVar string
	if o.Type != nil {
		typeVar = swag.FormatInt64(*o.Type)
	}
	if typeVar != "" {
		qs.Set("type", typeVar)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *NrActivityFavURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *NrActivityFavURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *NrActivityFavURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on NrActivityFavURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on NrActivityFavURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *NrActivityFavURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
