// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Field 场地
// swagger:model Field
type Field struct {

	// category Id
	CategoryID int64 `json:"categoryId,omitempty"`

	// checked time
	CheckedTime int64 `json:"checkedTime,omitempty"`

	// extra info1
	ExtraInfo1 string `json:"extraInfo1,omitempty"`

	// extra info2
	ExtraInfo2 string `json:"extraInfo2,omitempty"`

	// extra info3
	ExtraInfo3 int64 `json:"extraInfo3,omitempty"`

	// icon
	Icon string `json:"icon,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// publish time
	PublishTime int64 `json:"publishTime,omitempty"`

	// showicon
	Showicon bool `json:"showicon,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this field
func (m *Field) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Field) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Field) UnmarshalBinary(b []byte) error {
	var res Field
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
